---

- name: Download Logstash  {{ version }}
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-{{ version }}.deb
    dest: /tmp
  when: ansible_os_family == "Debian"

- name: Download Logstash  {{ version }}
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-{{ version }}.rpm
    dest: /tmp
  when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

- name: Install from a .deb package
  apt:
    deb: /tmp/logstash-{{ version }}.deb
  when: ansible_os_family == "Debian"

- name: Install from a .rpm package
  yum:
    name: /tmp/logstash-{{ version }}.rpm
    state: present
  when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

- name: Start service logstash, if not running
  service:
    name: logstash
    state: started

- name: Enable service logstash, and not touch the running state
  service:
    name: logstash
    enabled: yes

- name: Remove the downloaded package
  file:
    path: /tmp/logstash-{{ version }}.rpm
    state: absent
  when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

- name: Remove the downloaded package
  file:
    path: /tmp/logstash-{{ version }}.deb
    state: absent
  when: ansible_os_family == "Debian"

- name: Copy the logstash default conf
  template:
    src: ../templates/logstash.j2
    dest: /etc/logstash/logstash.yml
    owner: root
    group: root
    mode: '644'

- name: Restart the service
  service:
    name: logstash
    state: restarted