# Use HTTPS instead of HTTP
server.port: 5601
server.host: 0.0.0.0
elasticsearch.url: "https://localhost:9200"

# Configure the Kibana internal server user
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"

# Disable SSL verification because we use self-signed demo certificates
elasticsearch.ssl.verificationMode: none

# Whitelist the Search Guard Multi Tenancy Header
elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]
xpack.security.enabled: false
searchguard.auth.type: "basicauth"
searchguard.basicauth.login.brandimage: https://media.lovemondays.com.br/logos/231fb9/vr-beneficios-original.png
searchguard.basicauth.login.title: "Acesso ao Kibana"
searchguard.basicauth.login.subtitle: "Se você não possui acesso, solicite ao administrador do sistema."
searchguard.basicauth.login.buttonstyle: "Entrar"