---
- name: Download nginx
  yum:
    name: nginx
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: Install nginx
  yum:
    name: nginx
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: Install nginx 
  apt:
    name: ['nginx', 'nginx-common']
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Create alternative conf for '{{ app }}'
  template:
    src: ../templates/basic.conf
    dest: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0644
  when: app is defined
  ignore_errors: true


- name: Enable nginx service
  service:
    name: nginx
    enabled: yes
  notify: restart nginx