---
- name: Adding new group
  group:
    name: "{{ new_group }}"
    state: present

- name: Add the user(s) with a bash shell
  user:
    name: "{{ item.key }}"
    shell: "{{ shell }}"
    group: "{{ group_name }}"
    append: yes
    generate_ssh_key: no
  with_dict : "{{ users }}" 
  
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ lookup('file', '../files/{{ item.key }}.pub') }}"
  with_dict : "{{ users }}"    

- name: Removing password from the new user
  shell: passwd -d "{{ item.key }}"
  with_dict : "{{ users }}"
  