---
- name: add group
  group:
    name: "{{ new_group }}"
    state: present

- name: Add the user(s) "{{ user_name }}" with a bash shell, appending the groups "{{ new_group }}" and "{{ new_group }}".
  user:
    name: "{{ item.name }}"
    shell: "{{ shell }}"
    groups: "{{ item.groups }}"
    group: "{{ group_name }}"
    append: yes
    generate_ssh_key: no
  with_items:
   - { name: "{{ user_name }}", groups: "{{ new_group }}" }
  

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', '../files/{{ item.key }}.pub') }}"
  with_items:
    - { username: "{{ user_name }}", key: "{{ user_name }}" }
    

- name: remove the new user password
  shell: passwd -d "{{ item }}"
  with_items:
    - "{{ user_name }}"
  