---
- name: Update the repositories cache
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install some packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - "vim"
    - "tcpdump"
    - "dnsutils"
    - "whois"
  notify:
    - apt-get clean  