---
- name: Install NetData dependencies (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib1g-dev
    - uuid-dev
    - libmnl-dev
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - curl
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

- name: Install NetData dependencies (RedHat)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf 
    - automake
    - curl
    - gcc
    - git
    - libmnl-devel
    - libuuid-devel
    - make
    - MySQL-python
    - nc
    - pkgconfig
    - python
    - python-psycopg2
    - PyYAML
    - zlib-devel
  when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

- name: Creating directory
  file:
      path: "{{ netdata_path }}"
      state: directory

- name: Cloning the GIT repository
  git:
    repo: "{{ netdata_git }}"
    dest: "{{ netdata_path }}"
  
- name: Copying init
  copy:
    src: "{{ netdata_path }}/system/netdata-lsb.in"
    dest: /etc/init.d/netdata
    mode: 0755
    remote_src: yes
  when: ansible_distribution == "Amazon"

- name: Copying service
  copy:
    src: "{{ netdata_path }}/system/netdata.service.in"
    dest: /etc/systemd/system/
    mode: 0755
    remote_src: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"

- name: Run & Install NetData with a BashScript
  shell: "{{ netdata_script }} --dont-wait"
  args:
    chdir: "{{ netdata_path }}"
  notify:
    - restart netdata
 