---
- name: Add MariaDB repository (CentOS 6 and Amazon Linux)
  yum_repository:
    name: MariaDB
    description: MariaDB
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos6-amd64
    gpgcheck: no
    enabled: yes 
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" and ansible_distribution_version == "6"

- name: Add MariaDB repository (CentOS 7)
  yum_repository:
    name: MariaDB
    description: MariaDB
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64
    gpgcheck: no
    enabled: yes 
  when: ansible_distribution == "CentOS" and ansible_distribution_version == "7"
  
- name: Add an apt mariadb key by id from a keyserver (Ubuntu)
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '0xF1656F24C74CD1D8'
  when: ansible_distribution == "Ubuntu"

- name: Add an apt mariadb key by id from a keyserver (Debian)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0xcbcb082a1bb943db'
  when: ansible_distribution == "Debian"

- name: Add MariaDB repository (Ubuntu)
  apt_repository:
    repo: deb [arch=amd64,arm64,i386,ppc64el] http://mirror.ufscar.br/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ubuntu_version }} main
    state: present
    filename: mariadb
  when: ansible_distribution == "Ubuntu"

- name: Add MariaDB repository (Debian)
  apt_repository:
    repo: deb [arch=amd64,i386,ppc64el] http://mirror.ufscar.br/mariadb/repo/{{ mariadb_version }}/debian {{ debian_version }} main
    state: present
    filename: mariadb
  when: ansible_distribution == "Debian"

- name: Download and Install Mariadb server (Centos or Amazon Linux)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-mysqldb
    - mariadb-server
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: Download and Install Mariadb server (Debian or Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-mysqldb
    - mariadb-server
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

