---
- name: download and install java from debian family
  apt:
    name: "{{ java_apt }}"
    state: present
  when: ansible_os_family == "Debian"

- name: download and install java from redhat family 
  yum:
    name: "{{ java_rpm }}.x86_64"
    state: present
  when: ansible_distribution == "Amazon" or ansible_os_family == "CentOS"