---
- name: Add Jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Add Jenkins repository into system    
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Update repositories cache
  apt:
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Download and Install Jenkins
  apt:
    name: jenkins
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Add Jenkins repository (RedHat)
  yum_repository:
    name: jenkins
    description: Jenkins repo
    baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
  when: ansible_os_family == "RedHat"

- name: Import a Jenkins rpm key    
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  when: ansible_os_family == "RedHat"

- name: Download and Install Jenkins
  yum:
    name: jenkins
    state: present
  when: ansible_os_family == "RedHat"
