route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
            text: "*Details:* {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
            username: 'AlertManager'
            channel: '#alerts'
            api_url: 'https://hooks.slack.com/services/R4ND0M1/R4ND0M12/MYslackTOKEN12313'
            icon_emoji: ':prometheus:'
