---
- name: Grant a group {{ group }} rwx to an entire directory
  acl:
    path: "{{ item }}"
    entity: "{{ group }}"
    etype: group
    permissions: rwX
    state: present
    recursive: yes
  with_items:
    - ""
