---
- name: change timezone to "{{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: change locale to "{{ locale }}"
  locale_gen:
    name: "{{ locale }}"
    state: present
  when: ansible_os_family == "Debian"

- name: set locale to /etc/sysconfig/i18n
  replace: 
      path: /etc/sysconfig/i18n
      regexp: '^LANG=\"en_US\.UTF-8\"'
      replace: 'LANG="pt_BR.UTF-8"'    
  when: ansible_distribution == "Amazon"

- name: copy script check to /tmp
  copy:
    src: ../files/{{ script }}
    dest: /tmp
    mode: 0775

- name: executing the script
  shell: /tmp/{{ script }}
  register: bashrc

- name: check if LC_ALL variable exists (Debian family)
  shell: echo "export LC_ALL=pt_BR.UTF-8" >> /etc/bash.bashrc
  when: bashrc.stdout == "not found" and ansible_os_family == "Debian" 

- name: check if LC_ALL variables exists (Amazon Linux)  
  shell: echo "export LC_ALL=pt_BR.UTF-8" >> /etc/bashrc
  when: bashrc.stdout == "not found" and ansible_distribution == "Amazon" 

- name: removing script
  file:
    path: /tmp/{{ script }}
    state: absent