---
- name: Download docker script installation
  get_url:
    url: "{{ get_docker }}"
    dest: /tmp/docker.sh
    mode: 0775

- name: Executing docker.sh
  shell: /tmp/docker.sh
  
- name: Add user in a Docker group
  user: 
    user: "{{ user }}"
    groups: docker
    append: yes
  notify:
    - start docker