---

- name: Download PHP {{ version }}
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php{{ version }}-fpm
    - php{{ version }}-mysql
    - php{{ version }}-curl
    - php{{ version }}-gd
    - php{{ version }}-imap
    - php{{ version }}-xmlrpc
    - php{{ version }}-mcrypt
    - php{{ version }}-recode
    - php{{ version }}-tidy