---
- name: Upgrade all packages, excluding kernel & other related packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"
  
- name: Install a list of packages 
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - whois
  notify:
    - yum clean all